name: C/C++ CI

on: 
  push:
    branches: 
      - master
      - release/*
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: update subdependency
      run: ./scripts/feeds update -a 
    - name: install subdependency
      run: ./scripts/feeds install -a
    - name: config menu
      run: make -j1 V=s

