name: C/C++ CI

on: 
  push:
    branches: 
      - master
      - release/*
jobs:
  build:
    runs-on: ubuntu-14.04
    steps:
    - uses: actions/checkout@v1
    - name: install dependency
      run: sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
    - name: update subdependency
      run: ./scripts/feeds update -a 
    - name: install subdependency
      run: ./scripts/feeds install -a

